export const SET_PATHNAME: any = 'SET_PATHNAME';
export const SET_USER: any = 'SET_USER';

export const LOGOUT_USER: any = 'LOGOUT_USER';

// actions.js or actions.ts
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const VERIFY_USER_DATA = 'VERIFY_USER_DATA';
export const VERIFY_USER_DATA_SUCCESS = 'VERIFY_USER_DATA_SUCCESS';
export const VERIFY_USER_DATA_FAILURE = 'VERIFY_USER_DATA_FAILURE';

export const SIGN_UP_DATA = 'SIGN_UP_DATA';
export const SIGN_UP_DATA_SUCCESS = 'SIGN_UP_DATA_SUCCESS';
export const SIGN_UP_DATA_FAILURE = 'SIGN_UP_DATA_FAILURE';

export const FETCH_USER_METRICTS = 'FETCH_USER_METRICTS';
export const FETCH_USER_METRICTS_SUCCESS = 'FETCH_USER_METRICTS_SUCCESS';
export const FETCH_USER_METRICTS_FAILURE = 'FETCH_USER_METRICTS_FAILURE';

