export const SET_PATHNAME: any = 'SET_PATHNAME';
export const SET_USER: any = 'SET_USER';

export const LOGOUT_USER: any = 'LOGOUT_USER';

// actions.js or actions.ts
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const VERIFY_USER_DATA = 'VERIFY_USER_DATA';
export const VERIFY_USER_DATA_SUCCESS = 'VERIFY_USER_DATA_SUCCESS';
export const VERIFY_USER_DATA_FAILURE = 'VERIFY_USER_DATA_FAILURE';

export const SIGN_UP_DATA = 'SIGN_UP_DATA';
export const SIGN_UP_DATA_SUCCESS = 'SIGN_UP_DATA_SUCCESS';
export const SIGN_UP_DATA_FAILURE = 'SIGN_UP_DATA_FAILURE';

export const FETCH_USER_METRICTS = 'FETCH_USER_METRICTS';
export const FETCH_USER_METRICTS_SUCCESS = 'FETCH_USER_METRICTS_SUCCESS';
export const FETCH_USER_METRICTS_FAILURE = 'FETCH_USER_METRICTS_FAILURE';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';
// bot profile

export const CREATE_BOT_PROFILE = 'CREATE_BOT_PROFILE';
export const CREATE_BOT_PROFILE_SUCCESS = 'CREATE_BOT_PROFILE_SUCCESS';
export const CREATE_BOT_PROFILE_FAILURE = 'CREATE_BOT_PROFILE_FAILURE';

export const EDIT_BOT_PROFILE = 'EDIT_BOT_PROFILE';
export const EDIT_BOT_PROFILE_SUCCESS = 'EDIT_BOT_PROFILE_SUCCESS';
export const EDIT_BOT_PROFILE_FAILURE = 'EDIT_BOT_PROFILE_FAILURE';

export const GET_USER_BOT_PROFILE = 'GET_USER_BOT_PROFILE';
export const GET_USER_BOT_PROFILE_SUCCESS = 'GET_USER_BOT_PROFILE_SUCCESS';
export const GET_USER_BOT_PROFILE_FAILURE = 'GET_USER_BOT_PROFILE_FAILURE';

export const DELETE_BOT_PROFILE = 'DELETE_BOT_PROFILE';
export const DELETE_BOT_PROFILE_SUCCESS = 'DELETE_BOT_PROFILE_SUCCESS';
export const DELETE_BOT_PROFILE_FAILURE = 'DELETE_BOT_PROFILE_FAILURE';
// knowledge base
export const CREATE_KNOWLEDGE_BASE = 'CREATE_KNOWLEDGE_BASE';
export const CREATE_KNOWLEDGE_BASE_SUCCESS = 'CREATE_KNOWLEDGE_BASE_SUCCESS';
export const CREATE_KNOWLEDGE_BASE_FAILURE = 'CREATE_KNOWLEDGE_BASE_FAILURE';

export const GET_USER_KNOWLEDGE_BASE = 'GET_USER_KNOWLEDGE_BASE';
export const GET_USER_KNOWLEDGE_BASE_SUCCESS =
  'GET_USER_KNOWLEDGE_BASE_SUCCESS';
export const GET_USER_KNOWLEDGE_BASE_FAILURE =
  'GET_USER_KNOWLEDGE_BASE_FAILURE';

export const DELETE_USER_KNOWLEDGE_BASE = 'DELETE_USER_KNOWLEDGE_BASE';
export const DELETE_USER_KNOWLEDGE_BASE_SUCCESS =
  'DELETE_USER_KNOWLEDGE_BASE_SUCCESS';
export const DELETE_USER_KNOWLEDGE_BASE_FAILURE =
  'DELETE_USER_KNOWLEDGE_BASE_FAILURE';


// user chat data 
export const USER_CHAT_DATA = "USER_CHAT_DATA"
export const GET_USER_CHAT_SUCCESS = "GET_USER_CHAT_SUCCESS"
export const GET_USER_CHAT_FAILURE = "GET_USER_CHAT_FAILURE"
export const USER_ALL_SESSION = "USER_ALL_SESSION"
export const GET_USER_All_SESSION_SUCCESS = "GET_USER_All_SESSION_SUCCESS"
export const GET_USER_All_SESSION_FAILURE = "GET_USER_All_SESSION_FAILURE"
export const USER_OUESTION_SESSION = "USER_OUESTION_SESSION"
export const USER_SESSION_HISTORY = "USER_SESSION_HISTORY"
export const ADVANCE_FEATURE = "ADVANCE_FEATURE"
export const ADVANCE_FEATURE_SUCCESS = "ADVANCE_FEATURE_SUCCESS"
export const ADVANCE_FEATURE_FAILURE = "ADVANCE_FEATURE_FAILURE"
export const REMOVE_BOT_PROFILES = "REMOVE_BOT_PROFILES"
export const REMOVE_ADVANCE_FEATURE = "REMOVE_ADVANCE_FEATURE"
export const BOTSESSION_ID = "BOTSESSION_ID"
